### ISSUE TITLE
strengthen the case that one can deviate from the preregistration if it is obvious to the reader

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#219] opened 2021-09-16 07:12 UTC
Reviewer I argue that contrary to agile software development PAC requires researchers to foresee everything.

**Comment by cjvanlissa** [comment] 2021-09-16 11:47
Yes; I think this can be a feature, not a bug: Emphasize that necessary changes can be made, and documented in the commit messages AND a changelog.txt file. Example: https://github.com/cjvanlissa/manyanalysts_religion/compare/1f2a6bd..e38391d

**Comment by brandmaier** [comment] 2021-09-16 19:43
Seems to be a duplicate of #237.

**Closed** 2021-10-08 06:19 UTC
Labels: duplicate, Reviewer I
